"""empty message

Revision ID: 00bcbed91675
Revises: 6013b88ac5a6
Create Date: 2017-06-22 14:32:19.675680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00bcbed91675'
down_revision = '6013b88ac5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'article_ibfk_2', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key(u'article_ibfk_2', 'article', 'user', ['user_id'], ['id'])
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
