"""empty message

Revision ID: 5c654735d949
Revises: e48bdd7a7480
Create Date: 2017-06-22 18:04:53.526804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c654735d949'
down_revision = 'e48bdd7a7480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_time')
    # ### end Alembic commands ###
