"""empty message

Revision ID: 6013b88ac5a6
Revises: d6700c4d5ba1
Create Date: 2017-06-22 13:53:41.753487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6013b88ac5a6'
down_revision = 'd6700c4d5ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.drop_index('rolename', table_name='role')
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column('role', 'rolename')
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.add_column('role', sa.Column('rolename', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('rolename', 'role', ['rolename'], unique=True)
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'name')
    op.drop_column('role', 'default')
    # ### end Alembic commands ###
