"""empty message

Revision ID: e48bdd7a7480
Revises: 00bcbed91675
Create Date: 2017-06-22 14:49:19.029042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e48bdd7a7480'
down_revision = '00bcbed91675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image_path')
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'author_id')
    op.add_column('article', sa.Column('image_path', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
